const data: { [key: string]: any } = {
    users: [
        {
            id: 1,
            first_name: 'Darelle',
            last_name: 'Bagshaw',
            date: '06/12/1998',
            email: 'dbagshaw0@thetimes.co.uk',
            gender: 'Female',
            location: { city: 'Kotabaru', country: 'Indonesia' },
        },
        {
            id: 2,
            first_name: 'Ronny',
            last_name: 'Succamore',
            date: '04/01/1985',
            email: 'rsuccamore1@ft.com',
            gender: 'Male',
            location: { city: 'Yong’an', country: 'China' },
        },
        {
            id: 3,
            first_name: 'Cassie',
            last_name: 'Lomaz',
            date: '03/02/1982',
            email: 'clomaz2@infoseek.co.jp',
            gender: 'Male',
            location: { city: 'Awgu', country: 'Nigeria' },
        },
        {
            id: 4,
            first_name: 'Shaina',
            last_name: 'Kuller',
            date: '13/01/1999',
            email: 'skuller3@ucoz.com',
            gender: 'Female',
            location: { city: 'Tanqiao', country: 'China' },
        },
        {
            id: 5,
            first_name: 'Evaleen',
            last_name: 'Neasham',
            date: '14/10/1999',
            email: 'eneasham4@reuters.com',
            gender: 'Female',
            location: { city: 'Shikhazany', country: 'Russia' },
        },
        {
            id: 6,
            first_name: 'Nita',
            last_name: 'Haigh',
            date: '02/04/1990',
            email: 'nhaigh5@jimdo.com',
            gender: 'Female',
            location: { city: 'Serebryanyye Prudy', country: 'Russia' },
        },
        {
            id: 7,
            first_name: 'Wolfgang',
            last_name: 'Braithwait',
            date: '27/02/1984',
            email: 'wbraithwait6@booking.com',
            gender: 'Male',
            location: { city: 'Breia', country: 'Portugal' },
        },
        {
            id: 8,
            first_name: 'Ossie',
            last_name: 'McCheyne',
            date: '12/12/1982',
            email: 'omccheyne7@cornell.edu',
            gender: 'Male',
            location: { city: 'Panino', country: 'Russia' },
        },
        {
            id: 9,
            first_name: 'Waverley',
            last_name: 'MacAnespie',
            date: '19/04/1983',
            email: 'wmacanespie8@nasa.gov',
            gender: 'Male',
            location: { city: 'Cobre', country: 'Portugal' },
        },
        {
            id: 10,
            first_name: 'Saraann',
            last_name: 'Gobourn',
            date: '29/06/1997',
            email: 'sgobourn9@shop-pro.jp',
            gender: 'Female',
            location: { city: 'Shujāābād', country: 'Pakistan' },
        },
        {
            id: 11,
            first_name: 'Danny',
            last_name: 'Falloon',
            date: '27/05/1987',
            email: 'dfalloona@liveinternet.ru',
            gender: 'Female',
            location: { city: 'Dailekh', country: 'Nepal' },
        },
        {
            id: 12,
            first_name: 'Abbe',
            last_name: 'Hoble',
            date: '24/06/1990',
            email: 'ahobleb@mac.com',
            gender: 'Male',
            location: { city: 'Jinfeng', country: 'China' },
        },
        {
            id: 13,
            first_name: 'Rainer',
            last_name: 'Surcombe',
            date: '27/01/1997',
            email: 'rsurcombec@cnn.com',
            gender: 'Male',
            location: { city: 'Maguwon', country: 'Indonesia' },
        },
        {
            id: 14,
            first_name: 'Bron',
            last_name: 'Halton',
            date: '12/05/2000',
            email: 'bhaltond@zdnet.com',
            gender: 'Male',
            location: { city: 'Middleton', country: 'Canada' },
        },
        {
            id: 15,
            first_name: 'Andree',
            last_name: 'Glanert',
            date: '21/04/1988',
            email: 'aglanerte@booking.com',
            gender: 'Female',
            location: { city: 'Karangtanjung', country: 'Indonesia' },
        },
        {
            id: 16,
            first_name: 'Dru',
            last_name: 'Jordi',
            date: '22/03/1997',
            email: 'djordif@123-reg.co.uk',
            gender: 'Female',
            location: { city: 'Osek nad Bečvou', country: 'Czech Republic' },
        },
        {
            id: 17,
            first_name: 'Rory',
            last_name: 'Kilgrew',
            date: '14/10/1990',
            email: 'rkilgrewg@gov.uk',
            gender: 'Female',
            location: { city: 'Danao', country: 'Philippines' },
        },
        {
            id: 18,
            first_name: 'Marchall',
            last_name: 'Rotchell',
            date: '21/09/1988',
            email: 'mrotchellh@addthis.com',
            gender: 'Male',
            location: { city: 'Sumurasin', country: 'Indonesia' },
        },
        {
            id: 19,
            first_name: 'Lyndsay',
            last_name: 'Djurkovic',
            date: '21/04/1982',
            email: 'ldjurkovici@smh.com.au',
            gender: 'Female',
            location: { city: 'Danyang', country: 'China' },
        },
        {
            id: 20,
            first_name: 'Blisse',
            last_name: 'Landsborough',
            date: '23/01/2000',
            email: 'blandsboroughj@gmpg.org',
            gender: 'Female',
            location: { city: 'Shinan', country: 'China' },
        },
    ],
    apps: [
        {
            app_id: 'ca.google.Lotstring',
            app_name: 'Daltfresh',
            app_version: '8.79',
            app_domain: 'nifty.com',
            app_url: 'http://csmonitor.com',
        },
        {
            app_id: 'com.hao123.Duobam',
            app_name: 'Stim',
            app_version: '1.0',
            app_domain: 'google.pl',
            app_url: 'https://unblog.fr',
        },
        {
            app_id: 'org.un.Alpha',
            app_name: 'Hatity',
            app_version: '4.0',
            app_domain: 'rediff.com',
            app_url: 'http://irs.gov',
        },
        {
            app_id: 'com.msn.Bytecard',
            app_name: 'Treeflex',
            app_version: '4.73',
            app_domain: 'sogou.com',
            app_url: 'https://fema.gov',
        },
        {
            app_id: 'au.org.auda.Stim',
            app_name: 'Tres-Zap',
            app_version: '0.36',
            app_domain: 'scientificamerican.com',
            app_url: 'http://wikispaces.com',
        },
        {
            app_id: 'com.ucoz.Viva',
            app_name: 'Otcom',
            app_version: '3.6.6',
            app_domain: 'dailymail.co.uk',
            app_url: 'https://123-reg.co.uk',
        },
        {
            app_id: 'io.github.Latlux',
            app_name: 'Temp',
            app_version: '0.6.8',
            app_domain: 't-online.de',
            app_url: 'https://vkontakte.ru',
        },
        {
            app_id: 'com.elegantthemes.Temp',
            app_name: 'Lotlux',
            app_version: '8.35',
            app_domain: 'sogou.com',
            app_url: 'https://smh.com.au',
        },
        {
            app_id: 'ru.mail.Zathin',
            app_name: 'Lotstring',
            app_version: '0.11',
            app_domain: 'ft.com',
            app_url: 'http://hubpages.com',
        },
        {
            app_id: 'com.wired.Y-find',
            app_name: 'Mat Lam Tam',
            app_version: '2.24',
            app_domain: 'pinterest.com',
            app_url: 'http://mapy.cz',
        },
        {
            app_id: 'com.wufoo.Domainer',
            app_name: 'Bigtax',
            app_version: '0.39',
            app_domain: 'yahoo.com',
            app_url: 'http://flavors.me',
        },
        {
            app_id: 'com.sfgate.Sub-Ex',
            app_name: 'Quo Lux',
            app_version: '0.7.0',
            app_domain: 'toplist.cz',
            app_url: 'http://goo.gl',
        },
        {
            app_id: 'com.nationalgeographic.Fintone',
            app_name: 'Keylex',
            app_version: '0.2.2',
            app_domain: 'scientificamerican.com',
            app_url: 'http://reddit.com',
        },
        {
            app_id: 'com.istockphoto.It',
            app_name: 'Vagram',
            app_version: '8.60',
            app_domain: 'amazonaws.com',
            app_url: 'https://desdev.cn',
        },
        {
            app_id: 'com.friendfeed.Regrant',
            app_name: 'Vagram',
            app_version: '7.4',
            app_domain: 'nbcnews.com',
            app_url: 'http://slate.com',
        },
        {
            app_id: 'com.reference.Keylex',
            app_name: 'Tres-Zap',
            app_version: '9.34',
            app_domain: 'unblog.fr',
            app_url: 'https://theatlantic.com',
        },
        {
            app_id: 'com.wufoo.Fix San',
            app_name: 'Asoka',
            app_version: '3.4.2',
            app_domain: 'amazon.co.uk',
            app_url: 'https://ucoz.com',
        },
        {
            app_id: 'com.multiply.Holdlamis',
            app_name: 'Stringtough',
            app_version: '0.14',
            app_domain: 'apple.com',
            app_url: 'http://wunderground.com',
        },
        {
            app_id: 'com.weebly.Cookley',
            app_name: 'Prodder',
            app_version: '6.8.6',
            app_domain: 'gov.uk',
            app_url: 'http://godaddy.com',
        },
        {
            app_id: 'com.bloglines.Solarbreeze',
            app_name: 'Bitwolf',
            app_version: '0.69',
            app_domain: 'zimbio.com',
            app_url: 'http://blogger.com',
        },
    ],
    locations: [
        {
            city: 'Gastonia',
            country: 'United States',
            state: 'North Carolina',
            country_code: 'US',
            loc: { longitude: -81.1897, latitude: 35.284 },
            timezone: 'America/New_York',
        },
        {
            city: 'Honolulu',
            country: 'United States',
            state: 'Hawaii',
            country_code: 'US',
            loc: { longitude: -157.8795, latitude: 21.351 },
            timezone: 'Pacific/Honolulu',
        },
        {
            city: 'Irvine',
            country: 'United States',
            state: 'California',
            country_code: 'US',
            loc: { longitude: -117.8403, latitude: 33.7074 },
            timezone: 'America/Los_Angeles',
        },
        {
            city: 'Jacksonville',
            country: 'United States',
            state: 'Florida',
            country_code: 'US',
            loc: { longitude: -81.5864, latitude: 30.3704 },
            timezone: 'America/New_York',
        },
        {
            city: 'Brooklyn',
            country: 'United States',
            state: 'New York',
            country_code: 'US',
            loc: { longitude: -73.945, latitude: 40.6451 },
            timezone: 'America/New_York',
        },
        {
            city: 'San Jose',
            country: 'United States',
            state: 'California',
            country_code: 'US',
            loc: { longitude: -121.8601, latitude: 37.2187 },
            timezone: 'America/Los_Angeles',
        },
        {
            city: 'Springfield',
            country: 'United States',
            state: 'Illinois',
            country_code: 'US',
            loc: { longitude: -89.606, latitude: 39.7495 },
            timezone: 'America/Chicago',
        },
        {
            city: 'Philadelphia',
            country: 'United States',
            state: 'Pennsylvania',
            country_code: 'US',
            loc: { longitude: -75.1179, latitude: 40.0018 },
            timezone: 'America/New_York',
        },
        {
            city: 'Boynton Beach',
            country: 'United States',
            state: 'Florida',
            country_code: 'US',
            loc: { longitude: -80.1124, latitude: 26.5354 },
            timezone: 'America/New_York',
        },
        {
            city: 'Houston',
            country: 'United States',
            state: 'Texas',
            country_code: 'US',
            loc: { longitude: -95.3121, latitude: 29.7758 },
            timezone: 'America/Chicago',
        },
        {
            city: 'Mc Keesport',
            country: 'United States',
            state: 'Pennsylvania',
            country_code: 'US',
            loc: { longitude: -80.0248, latitude: 40.4344 },
            timezone: 'America/New_York',
        },
        {
            city: 'Atlanta',
            country: 'United States',
            state: 'Georgia',
            country_code: 'US',
            loc: { longitude: -84.4226, latitude: 33.7629 },
            timezone: 'America/New_York',
        },
        {
            city: 'Chattanooga',
            country: 'United States',
            state: 'Tennessee',
            country_code: 'US',
            loc: { longitude: -85.2091, latitude: 35.2211 },
            timezone: 'America/New_York',
        },
        {
            city: 'Salt Lake City',
            country: 'United States',
            state: 'Utah',
            country_code: 'US',
            loc: { longitude: -111.9083, latitude: 40.6681 },
            timezone: 'America/Denver',
        },
        {
            city: 'Springfield',
            country: 'United States',
            state: 'Illinois',
            country_code: 'US',
            loc: { longitude: -89.606, latitude: 39.7495 },
            timezone: 'America/Chicago',
        },
        {
            city: 'Lexington',
            country: 'United States',
            state: 'Kentucky',
            country_code: 'US',
            loc: { longitude: -84.4583, latitude: 38.0612 },
            timezone: 'America/New_York',
        },
        {
            city: 'Wichita',
            country: 'United States',
            state: 'Kansas',
            country_code: 'US',
            loc: { longitude: -97.4269, latitude: 37.7639 },
            timezone: 'America/Chicago',
        },
        {
            city: 'Springfield',
            country: 'United States',
            state: 'Illinois',
            country_code: 'US',
            loc: { longitude: -89.606, latitude: 39.7495 },
            timezone: 'America/Chicago',
        },
        {
            city: 'Helena',
            country: 'United States',
            state: 'Montana',
            country_code: 'US',
            loc: { longitude: -112.0402, latitude: 46.5901 },
            timezone: 'America/Denver',
        },
        {
            city: 'Wilmington',
            country: 'United States',
            state: 'North Carolina',
            country_code: 'US',
            loc: { longitude: -77.8526, latitude: 34.0881 },
            timezone: 'America/New_York',
        },
    ],
};

export default data;
